server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "+pEnwIGKDjxL9DglAHygyWDUndbFOl1fZLdKf1YioeV2PBAL+tJYPNJwxwBwwwOU"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds